import { localDateKey } from "../utils/dates.js";
export const defaultFolders = [
  { id: "inbox", name: "Inbox", color: "bg-slate-400", taskCount: 0 },
  { id: "computer-science", name: "Computer Science", color: "bg-coral" },
  { id: "spanish", name: "Spanish", color: "bg-sage" },
  { id: "research", name: "Research", color: "bg-clay" },
  { id: "internship", name: "Internship", color: "bg-ink" },
  { id: "business", name: "Business", color: "bg-amber-400" },
  { id: "personal", name: "Personal", color: "bg-emerald-400" },
  { id: "finance", name: "Finance", color: "bg-sky-400" },
];

export const defaultFilters = {
  search: "",
  priority: "All",
  folderId: "All",
  status: "All",
};

export const defaultTasks = [
  {
    id: "cs-1",
    title: "Finish Systems Lab",
    description: "Complete the process scheduling write-up and submit the lab files.",
    folderId: "computer-science",
    status: "active",
    priority: "High",
    dueDate: localDateKey(),
    estimate: "4h",
    storyPoints: 5,
    notes: "Needs the longest uninterrupted work block.",
    subtasks: [
      { id: "cs-1-a", title: "Run final tests", completed: true },
      { id: "cs-1-b", title: "Write README notes", completed: false },
      { id: "cs-1-c", title: "Submit to Codio", completed: false },
    ],
  },
  {
    id: "cs-2",
    title: "Read data structures chapter",
    description: "Review heaps and graph traversal examples.",
    folderId: "computer-science",
    status: "active",
    priority: "Medium",
    dueDate: "",
    estimate: "45m",
    storyPoints: 2,
    notes: "",
    subtasks: [],
  },
  {
    id: "cs-3",
    title: "Study for operating systems quiz",
    description: "Review synchronization, scheduling, and memory notes.",
    folderId: "computer-science",
    status: "active",
    priority: "High",
    dueDate: "",
    estimate: "2h",
    storyPoints: 3,
    notes: "",
    subtasks: [],
  },
  {
    id: "sp-1",
    title: "Study vocab",
    description: "Practice the new Spanish vocabulary set.",
    folderId: "spanish",
    status: "active",
    priority: "Medium",
    dueDate: "",
    estimate: "30m",
    storyPoints: 1,
    notes: "",
    subtasks: [],
  },
  {
    id: "sp-2",
    title: "Complete discussion post",
    description: "Write and submit this week's Spanish discussion response.",
    folderId: "spanish",
    status: "active",
    priority: "Low",
    dueDate: "",
    estimate: "25m",
    storyPoints: 1,
    notes: "",
    subtasks: [],
  },
  {
    id: "re-1",
    title: "Finish GUI update",
    description: "Polish the latest research GUI workflow.",
    folderId: "research",
    status: "active",
    priority: "High",
    dueDate: "",
    estimate: "2h",
    storyPoints: 3,
    notes: "Ask for feedback after the update is staged.",
    subtasks: [],
  },
  {
    id: "re-2",
    title: "Review FIXS documentation",
    description: "Read docs and capture implementation notes.",
    folderId: "research",
    status: "active",
    priority: "Medium",
    dueDate: "",
    estimate: "1h",
    storyPoints: 2,
    notes: "",
    subtasks: [],
  },
  {
    id: "in-1",
    title: "Make recruiting plan",
    description: "Draft target companies and weekly application cadence.",
    folderId: "internship",
    status: "active",
    priority: "High",
    dueDate: "",
    estimate: "1h",
    storyPoints: 2,
    notes: "",
    subtasks: [],
  },
  {
    id: "in-2",
    title: "Update resume bullet",
    description: "Rewrite the latest project bullet with measurable impact.",
    folderId: "internship",
    status: "active",
    priority: "Medium",
    dueDate: "",
    estimate: "35m",
    storyPoints: 1,
    notes: "",
    subtasks: [],
  },
  {
    id: "bu-1",
    title: "Build waitlist landing page",
    description: "Finalize copy and demo sections.",
    folderId: "business",
    status: "active",
    priority: "High",
    dueDate: "",
    estimate: "3h",
    storyPoints: 4,
    notes: "",
    subtasks: [],
  },
  {
    id: "bu-2",
    title: "Draft TikTok content ideas",
    description: "Create short-form content hooks for launch.",
    folderId: "business",
    status: "active",
    priority: "Low",
    dueDate: "",
    estimate: "45m",
    storyPoints: 1,
    notes: "",
    subtasks: [],
  },
  {
    id: "co-1",
    title: "Sign up for Codio",
    description: "Account setup complete.",
    folderId: "computer-science",
    status: "completed",
    priority: "Low",
    dueDate: "",
    estimate: "10m",
    storyPoints: 1,
    notes: "",
    subtasks: [],
  },
  {
    id: "co-2",
    title: "Pay Apple storage",
    description: "Monthly storage bill handled.",
    folderId: "finance",
    status: "completed",
    priority: "Low",
    dueDate: "",
    estimate: "5m",
    storyPoints: 1,
    notes: "",
    subtasks: [],
  },
  {
    id: "co-3",
    title: "Add assignments to calendar",
    description: "Initial assignment import completed.",
    folderId: "personal",
    status: "completed",
    priority: "Medium",
    dueDate: "",
    estimate: "25m",
    storyPoints: 1,
    notes: "",
    subtasks: [],
  },
];
