export const initialColumns = [
  {
    id: "computer-science",
    title: "Computer Science",
    color: "bg-coral",
    tasks: [
      {
        id: "cs-1",
        title: "Finish Systems Lab",
        dueDate: "Tomorrow",
        priority: "High",
        estimate: "4h",
        tag: "CS",
      },
      {
        id: "cs-2",
        title: "Read data structures chapter",
        dueDate: "Wed",
        priority: "Medium",
        estimate: "45m",
        tag: "CS",
      },
      {
        id: "cs-3",
        title: "Study for operating systems quiz",
        dueDate: "Fri",
        priority: "High",
        estimate: "2h",
        tag: "OS",
      },
    ],
  },
  {
    id: "spanish",
    title: "Spanish",
    color: "bg-sage",
    tasks: [
      {
        id: "sp-1",
        title: "Study vocab",
        dueDate: "Today",
        priority: "Medium",
        estimate: "30m",
        tag: "Spanish",
      },
      {
        id: "sp-2",
        title: "Complete discussion post",
        dueDate: "Thu",
        priority: "Low",
        estimate: "25m",
        tag: "Spanish",
      },
    ],
  },
  {
    id: "research",
    title: "Research",
    color: "bg-clay",
    tasks: [
      {
        id: "re-1",
        title: "Finish GUI update",
        dueDate: "Fri",
        priority: "High",
        estimate: "2h",
        tag: "Lab",
      },
      {
        id: "re-2",
        title: "Review FIXS documentation",
        dueDate: "Next week",
        priority: "Medium",
        estimate: "1h",
        tag: "Research",
      },
    ],
  },
  {
    id: "internship",
    title: "Internship",
    color: "bg-ink",
    tasks: [
      {
        id: "in-1",
        title: "Make recruiting plan",
        dueDate: "Sun",
        priority: "High",
        estimate: "1h",
        tag: "Career",
      },
      {
        id: "in-2",
        title: "Update resume bullet",
        dueDate: "Mon",
        priority: "Medium",
        estimate: "35m",
        tag: "Resume",
      },
    ],
  },
  {
    id: "business",
    title: "Business",
    color: "bg-amber-400",
    tasks: [
      {
        id: "bu-1",
        title: "Build waitlist landing page",
        dueDate: "Today",
        priority: "High",
        estimate: "3h",
        tag: "Startup",
      },
      {
        id: "bu-2",
        title: "Draft TikTok content ideas",
        dueDate: "Sat",
        priority: "Low",
        estimate: "45m",
        tag: "Content",
      },
    ],
  },
  {
    id: "completed",
    title: "Completed",
    color: "bg-emerald-500",
    tasks: [
      {
        id: "co-1",
        title: "Sign up for Codio",
        dueDate: "Done",
        priority: "Done",
        estimate: "10m",
        tag: "CS",
      },
      {
        id: "co-2",
        title: "Pay Apple storage",
        dueDate: "Done",
        priority: "Done",
        estimate: "5m",
        tag: "Finance",
      },
      {
        id: "co-3",
        title: "Add assignments to calendar",
        dueDate: "Done",
        priority: "Done",
        estimate: "25m",
        tag: "Planning",
      },
    ],
  },
];
